### ISSUE TITLE
Test flakes

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/fabric-chaincode-java#203]
There are currently a couple of tests which are failing randomly(?) which would be good to fix.

The first was introduced with the new OpenTelemetry support recently and is now the most common failure in the [interop tests](https://dev.azure.com/Hyperledger/Fabric-Test/_build?definitionId=114&_a=summary)...

```
2021-10-05T15:47:00.0941330Z OpenTelemetryTracesProviderTest > testTracing() FAILED
2021-10-05T15:47:00.0941865Z     org.junit.ComparisonFailure: expected:<[fals]e> but was:<[tru]e>
2021-10-05T15:47:00.0942423Z         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2021-10-05T15:47:00.0943148Z         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
2021-10-05T15:47:00.0943871Z         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2021-10-05T15:47:00.0944667Z         at org.hyperledger.fabric.traces.impl.OpenTelemetryTracesProviderTest.testTracing(OpenTelemetryTracesProviderTest.java:194)
22:41
```

This test is also flaking often...

```
2021-10-05T00:19:29.2819784Z org.hyperledger.fabric.contract.ContractRouterTest > testStartingContractRouterWithStartingAChaincodeServer FAILED
2021-10-05T00:19:29.2820502Z     java.lang.AssertionError: 
2021-10-05T00:19:29.2821015Z     Expected: is <SUCCESS>
2021-10-05T00:19:29.2821532Z          but: was <INTERNAL_SERVER_ERROR>
2021-10-05T00:19:29.2822693Z         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
2021-10-05T00:19:29.2823320Z         at org.junit.Assert.assertThat(Assert.java:956)
2021-10-05T00:19:29.2823924Z         at org.junit.Assert.assertThat(Assert.java:923)
2021-10-05T00:19:29.2824667Z         at org.hyperledger.fabric.contract.ContractRouterTest.testStartingContractRouterWithStartingAChaincodeServer(ContractRouterTest.java:428)
```

**Comment by atoulme** [comment]
On it.
