### ISSUE TITLE
InvocationTaskManager sendToTask Failed to send response to the task hasmap missing entry

### ISSUE THREAD

**Issue by aawhitetech** [hyperledger/fabric-chaincode-java#306]
**Version: 2.2.0**

One of my chaincode peers is occasionally failing transactions with the following error:

```
15:37:45:121 INFO    org.hyperledger.fabric.contract.ContractRouter processRequest                    Got invoke routing request
15:37:45:122 INFO    org.hyperledger.fabric.contract.ContractRouter processRequest                    Got the invoke request for:ProductContract:get [7LZ4W7MTRfgHU70ABNQf8Qv5KWHo3x9v]
15:37:45:125 INFO    org.hyperledger.fabric.contract.ContractRouter processRequest                    Got routing:get:com.contracts.ProductContract
15:37:45:128 INFO    org.hyperledger.fabric.shim.impl.ChaincodeInvocationTask invoke                  Sending message to the peer 79e6be839fb05cde256d58750999c6f94654ebef51203e784e39dd94f053f84b
15:37:45:136 SEVERE  org.hyperledger.fabric.shim.impl.InvocationTaskManager sendToTask                Failed to send response to the task task 79e6be839fb05cde256d58750999c6f94654ebef51203e784e39dd94f053f84bTask hasmap missing entry
java.lang.InterruptedException: Task hasmap missing entry
        at org.hyperledger.fabric.shim.impl.InvocationTaskManager.sendToTask(InvocationTaskManager.java:191)
        at org.hyperledger.fabric.shim.impl.InvocationTaskManager.handleMsg(InvocationTaskManager.java:166)
        at org.hyperledger.fabric.shim.impl.InvocationTaskManager.onChaincodeMessage(InvocationTaskManager.java:139)
        at org.hyperledger.fabric.shim.impl.ChaincodeSupportClient$1.onNext(ChaincodeSupportClient.java:96)
        at org.hyperledger.fabric.shim.impl.ChaincodeSupportClient$1.onNext(ChaincodeSupportClient.java:92)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:447)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInternal(ClientCallImpl.java:658)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:643)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
The other chaincode peers successfully processed the transaction however, this one did not.

I'm trying to understand why this issue is occuring. It seems as though the task no longer exists to receive the chaincode message but I don't know enough as to what would cause this to happen.

I later start seeing it more and more and then eventually the peer times out every transaction. Perhaps this is unrelated but always seems to be the outcome.

**Comment by bestbeforetoday** [comment]
Does this problem occur with the latest release of Fabric and _fabric-chaincode-java_ (v2.5.0)? If you are not able to use Fabric v2.5, is the problem still present with _fabric-chaincode-java_ v2.2.3?

**Comment by aawhitetech** [comment]
Unfortunately, I'm no longer in a position to further test or develop upon the issue. I'm going to close this issue and will reopen in the future if anything changes.
